services:
  postgres:
    image: postgres:latest
    container_name: zoomo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zoomodb
      POSTGRES_USER: krmla
      POSTGRES_PASSWORD: krmla
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /home/kirmola/Downloads:/data:rw


volumes:
  pgdata:
