# Generated by Django 5.2 on 2025-04-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='movie title')),
                ('original_title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='rating')),
                ('vote_count', models.IntegerField(default=0, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
                ('spoken_languages', models.JSONField(default=list)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('extra_images', models.JSONField(default=list)),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('downlinks', models.JSONField(default=list, verbose_name='download links')),
                ('fileid', models.CharField(max_length=50, verbose_name='terabox file id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('similar_movies', models.ManyToManyField(blank=True, to='frontend.movie')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
