# Generated by Django 5.2 on 2025-04-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='downlinks',
            field=models.JSONField(default=list, verbose_name='download links'),
        ),
    ]
