# Generated by Django 5.2 on 2025-04-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_movie_downlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fileid',
            field=models.CharField(default=None, max_length=50, verbose_name='terabox file id'),
            preserve_default=False,
        ),
    ]
