# Generated by Django 5.2 on 2025-04-05 11:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_movie_fileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['title', 'fileid']),
        ),
    ]
